# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              Blockstack
description:        Docs

# Site subpath, e.g. /blog
baseurl:            ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
# permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.com
url:                "https://docs.blockstack.org"

repository: moxiegirl/docs.blockstack
staticman:
  branch: "master"
# github_editme_path: moxiegirl/docs-new/blob/master
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.


# Site logo, image or text
brand:
    image:         logo.png  # e.g. logo.png, upload logo image file to /assets/img/ folder
    text:          Docs      # if the above "logo:" image variable  is not set, this text logo is displayed instead

# Default author settings
author:
    name:       Blockstack
    github:     Blockstack    # Github username for avatar

# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
    peter:
        name:       Peter Brown
        github:     PressApps    # Github username for avatar

# Social icons displayed in footer
social:
    email:
    website:
    facebook:       https://www.facebook.com/
    flickr:
    dribbble:
    github:
    googleplus:
    instagram:      https://www.instagram.com/
    linkedin:
    pinterest:
    twitter:        https://twitter.com/
    vimeo:          https://vimeo.com/
    youtube:

# Twitter share button
twitter:
  username: blockstack
  image: /assets/img/touch-icon.png
  card: summary


# Default footer image settings
footer:
    copyright:      "Blockstack Public Benefit Corp."

# Disqus comments shortname, requires Disqus account https://disqus.com/
# disqus:
#     shortname:      # 1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics: UA-125894815-1

# Google maps API key, get your key here: https://developers.google.com/maps/documentation/javascript/get-api-key
google_maps_api_key:

# Number of posts displayed on blog page
paginate: 10

# Blog path
paginate_path:      "/news/:num/"

# Path to post content assets directory i.e post images, pdfs etc
post_assets:        /assets/posts/
#keep_files:  (`/images/`)


# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
toc:
  min_level: 2 # default: 1
  max_level: 3 # default: 6
  list_class: "uk-nav uk-nav-default"
  sublist_class: "uk-nav-sub doc-nav"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
  - jekyll-titles-from-headings
  - jekyll-sitemap
  - jekyll-toc

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

include:
  - _redirects
  - _data
exclude:
  - package-lock.json
  - package.json
  - Guardfile
  - '*/glossary.md'
  - '*/README.md'
  - README.md
  - THEME_README.md
  - Gemfile
  - Gemfile.lock
  - 'node_modules'
  - collections.json
  - get-content.sh
  - _core/aglio_templates
  - _core/attic
  - _core/api-specs.md
  - _core/setup_core_portal.md
  - _core/advanced_usage.md
  - _core/atlas_network.md
  - _core/basic_usage.md
  - _core/blockstack_naming_service.md
  - _core/cli.md
  - _core/faq_evaluators.md
  - _core/gai.md
  - _core/glossary.md
  - _core/interactive_regtest_macros.md
  - _core/namespace_creation.md
  - _core/openbazaar.md
  - _core/resolver.md
  - _core/search.md
  - _core/subdomain.md
  - _data/*.yml
  - _data/*.csv
  - _data/cliRef.json
  - _storage/digital-ocean-deploy.md

sass:
  style:            compressed

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      comments: true
      image: /assets/img/touch-icon.png
      description: "Using the Blockstack Ecosystem to develop decentralized applications (DApps). "

collections:
  android:
    output: true
    basepath: "blockstack/blockstack-android/blob/master/docs"
  community:
    output: true
    basepath: "blockstack/blockstack-core/blob/master/docs"
  core:
    output: true
    basepath: "blockstack/blockstack-core/blob/master/docs"
  develop:
    output: true
    basepath: "moxiegirl/docs.blockstack"
  storage:
    output: true
    basepath: "blockstack/gaia/blob/master/docs"
  browser:
    output: true
    basepath: "blockstack/blockstack-browser/blob/master/docs"
  ios:
    output: true
    basepath: "blockstack/blockstack-ios/blob/master/docs"
  common:
    output: true
    basepath: "moxiegirl/docs.blockstack"
  org:
    output: true
    basepath: "moxiegirl/docs.blockstack"
