name: stylecheck
on:
  pull_request:
    branches: [master]
    paths:
      - '**.md'

jobs:
  stylecheck:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: get changed Files
        id: get_changed_files
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: run vale
        uses: errata-ai/vale-action@master
        with:
          files: '${{ steps.get_changed_files.outputs.all }}'
          onlyAnnotateModifiedLines: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
